Installation for Windows
Flow-Based-Cartograms/go_cart pull request #15
Opened 2020-01-03 00:29 UTC by krosenfeld

I am starting to use cartogram on windows using cygwin.  I had to install libcjson by hand and so added some installation notes to the README.md.

2020-01-03 15:17 UTC, mgastner commented
Thank you for working on a Windows installation! I'm not so familiar with Windows. So I apologize in advance for my naivety, but it makes me a good test rabbit. Suppose I succeeded installing cJSON. (I may need to get back to you about cJSON later on.) What shall I do next to build the cartogram generator?
```
./autobuild.sh
Warning: Your environment is currently not supported by autobuild.
./autobuild.sh: line 12: ./configure: No such file or directory
```
The warning isn't fatal, so that we should be able to ignore it for the time being. Does `autobuild.sh` fail to make  `./configure` because I still need to install some tool from cygwin? I've installed everything in the Devel category.

2020-01-03 17:24 UTC, krosenfeld commented
My apologies -- I had forgotten a few steps:

1. Run [dos2unix ](https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile) on autogen.sh and autobuild.sh to convert newline characters
2. Run autogen.sh 
3. And then follow build directions for maxOs and linux

2020-01-03 18:48 UTC, mgastner commented
Thank you very much! I managed to generate my first cartogram under Windows.

In your explanation in README.md how to install cJSON, wouldn't I need to run `make` before `make install`? At least in my case, `./autobuild.sh` only succeeded after running `make`.

2020-01-03 23:51 UTC, krosenfeld commented
You are correct - `make` should build before `make install` copies files.

2020-01-04 08:58 UTC, mgastner commented
Thanks so much for your contribution! If you could please add `make` in the cJSON installation, the two `dos2unix` commands and `./autogen.sh`, I'll be delighted to merge your pull request.

2020-01-04 18:26 UTC, krosenfeld commented
Thank you for the detailed review.  I've updated my branch and the changes are showing in the pull request.  Any further changes you would suggest?

2020-01-06 20:40 UTC, pratyushmore commented
Hello @krosenfeld, thank you so much for your contribution. 

Making the cartogram generator available on Windows would truly be a great addition. 

I have a few comments/questions:

* While I've worked with cygwin in the past, I wonder whether the Bash Shell for Windows 10 (https://itsfoss.com/install-bash-on-windows/) allows for a better Linux-like experience on Windows? Are you using Windows 10? If yes, have you tried this out? 
@mgastner are you using Windows 10? Would you be able to test this? Unfortunately I do not have access to a Windows computer, and thus cannot try it out myself!

* If you are not using Windows 10, and want to include instructions for past editions of Windows, perhaps you could modify the README to clarify that these instructions are for older versions of Windows?

2020-01-06 21:16 UTC, krosenfeld commented
Hi @pratyushmore,

I have worked with cygwin for multiple projects in the past, but never used the bash shell for windows 10.  This looks very interesting as Cygwin takes up a lot of memory. One drawback, as you point out, is that it would require separate instructions for past editions of Windows.

2020-01-06 21:50 UTC, pratyushmore commented
@krosenfeld are you using Windows 10? If yes, could you try using the Bash for Windows? 

If it works for you, I'm inclined to simply add instructions for Windows 10 until someone asks for support for previous versions! 😄

2020-01-06 22:25 UTC, krosenfeld commented
@pratyushmore 

I do have windows 10 and the install/build was very smooth.   This seems like a nice solution to me!  I've updated the Readme on the pull request so that the default install is windows 10 and instructions for earlier editions are in the troubleshooting section.

2020-01-07 21:46 UTC, pratyushmore requested changes
Glad to know it worked :D 

Added comments, and requested some changes. After this the PR should be good to go!

2020-01-07 21:46 UTC, pratyushmore commented on README.md
> +### Building (Window 10)
I would put this in the Dependencies section instead of a separate Building section. Also, nit: Windows 10 instead of Window 10.

2020-01-07 21:46 UTC, pratyushmore commented on README.md
> +1. Enable Linux on your machine and install Ubuntu following <a href='https://itsfoss.com/install-bash-on-windows/'>these instructions</a>.
Install Bash for Windows following ...

2020-01-07 21:46 UTC, pratyushmore commented on README.md
> +2. Follow instructions below for building on Linux
Use this Bash terminal in the build steps.

2020-01-07 21:46 UTC, pratyushmore commented on README.md
> +### Building (macOS & Linux)
You can then make this Building (macOS, Linux & Windows)

2020-01-07 21:46 UTC, pratyushmore commented on README.md
> +#### Windows
If we're including this anyway, it's best to keep it in the dependencies section below the part for Windows 10

2020-01-07 21:47 UTC, pratyushmore commented on README.md
> +1. Enable Linux on your machine and install Ubuntu following <a href='https://itsfoss.com/install-bash-on-windows/'>these instructions</a>.
(It's not really installing Linux/Ubuntu)

2020-01-07 23:40 UTC, krosenfeld commented
Done! Let me know if there are further changes you would suggest.

2020-01-08 07:08 UTC, pratyushmore commented on README.md
> +#### Windows
@krosenfeld I think you missed out the first part of this comment :D 

I'd move this to the dependencies section as it makes more sense there!

2020-01-08 07:09 UTC, pratyushmore commented
Think you missed out one comment :)

2020-01-08 21:55 UTC, krosenfeld commented
Got it!  Thanks for catching that.

2020-01-08 22:34 UTC, pratyushmore approved these changes

2020-01-08 22:35 UTC, merged

2020-01-08 22:35 UTC, pratyushmore commented
It's in! Thank you so much :)