Enable color input for regions (#14)
Flow-Based-Cartograms/go_cart pull request #22
Opened 2020-08-10 00:35 UTC by johnyrufus

2020-08-18 13:48 UTC, mgastner commented on cartogram_generator/fill_with_density.c
> +    b = 0.70;
After dividing by 255 in lines 315-317, the fill colors are essentially black, so the default fill color (black) is indistinguishable from the default border color (also black). Please change to r = 245.0, g = 235.0, b = 179.0.

2020-08-18 13:49 UTC, mgastner requested changes
Please make default values for r, g, b larger.

2020-08-18 14:51 UTC, johnyrufus commented
Thanks for pointing this out. I modified the default values.

2020-08-26 07:38 UTC, merged

2020-08-26 07:39 UTC, mgastner commented
Thank you for adding the color option!